title: Ankita Duttagupta# your name (or website title) here
logo: "/images/IMG_20200712_152130_935_1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am Ankita Duttagupta.This is my Github Portfolio!
  <br><br>
  
  <br><br>
  <a href="https://"www.linkedin.com/in/ankitadg97">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
