title: Ankita Duttagupta # your name (or website title) here
logo: "/images/ankita.png.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am Ankita Duttagupta.This is my Github Portfolio!
  <br>
  <a href="www.linkedin.com/in/ankitadg97">View My LinkedIn Profile</a> 
   <br>
  <a href="ankitadg97@gmail.com">Contact ID</a> 
   <br>
  
